spring:
  application:
    name: tutor-chatgpt
  ai:
    openai:
      api-key:
      memory:
        repository:
          jdbc:
            platform: auto-detected
            initialize-schema: never
