spring:
  application:
    name: tutor-chatgpt
  ai:
    openai:
      api-key: ${OPENAPI_KEY}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
            platform: auto-detected
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/tutor}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migrations
    enabled: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  shell:
    interactive:
      enabled: false
    command:
      script:
        enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

minio:
  endpoint: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ADMIN}
  secret-key: ${MINIO_PASSWORD}
  bucket: chat-images

management:
  endpoints:
    jmx:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

server:
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  refresh-expiration: 3600000
